### ISSUE TITLE
Do we have support for Location data with altitude?

### ISSUE THREAD

**Issue by sudhamani1983** [FraunhoferIOSB/SensorThingsServer#25]
I tried inserting Location with altitude, but I can't find any difference in geometry data inserted in "Location" table (Ignores altitude). 

**Example:**

**Location JSON without altitude :** 
{
  "name": "IONOrchard-without-Alt",
  "encodingType": "application/geo+json",
  "description": "IONOrchard-without-Alt",
  "location": {
	  "type": "Polygon",
	  "coordinates": [
	   [
	    [103.83118689, 1.30408219], 
	    [103.83193523, 1.30451928], 
	    [103.83253068, 1.30403392],
	    [103.83200765, 1.30352175],
	    [103.83118689, 1.30408219]
	   ]
	  ]
	}
}

**GEOM value :** 

0103000020110F00000100000005000000233C4C5BC40B664129C65F68F2B8014140620DC5CE0B66419D8EFDC277BA0141B2AA2D0ED70B6641C013D168C7B801412A4D07C7CF0B6641714DE02CFFB60141233C4C5BC40B664129C65F68F2B80141

**Location JSON with :** 
{
  "name": "IONOrchard",
  "encodingType": "application/geo+json",
  "description": "IONOrchard",
  "location": {
	  "type": "Polygon",
	  "coordinates": [
	   [
	    [103.83118689, 1.30408219, 26], 
	    [103.83193523, 1.30451928, 22], 
	    [103.83253068, 1.30403392, 22],
	    [103.83200765, 1.30352175, 24],
	    [103.83118689, 1.30408219, 26]
	   ]
	  ]
	}
}

**GEOM value :** 

0103000020110F00000100000005000000233C4C5BC40B664129C65F68F2B8014140620DC5CE0B66419D8EFDC277BA0141B2AA2D0ED70B6641C013D168C7B801412A4D07C7CF0B6641714DE02CFFB60141233C4C5BC40B664129C65F68F2B80141

**Comment by hylkevds** [comment]
Currently the GEOM is flattened using ST_Force2D, though the Z-value is kept in the json. So currently the spatial functions all ignore the z value.

I can look into changing this to always use 3D instead.

**Comment by hylkevds** [comment]
Just had a quick look, and I think the biggest problem is that the geospatial functions, and WKT are not very helpful in 3D. There is no st_above or st_below or something like that. You could use st_within, with a 3D object, but the only 3D object types WKT supports are Polyhedralsurface and TIN, which are very unwieldy. The "simple" 3d box would end up being:

```
POLYHEDRALSURFACE Z (
  ((0 0 0, 0 1 0, 1 1 0, 1 0 0, 0 0 0)),
  ((0 0 0, 0 1 0, 0 1 1, 0 0 1, 0 0 0)),
  ((0 0 0, 1 0 0, 1 0 1, 0 0 1, 0 0 0)),
  ((1 1 1, 1 0 1, 0 0 1, 0 1 1, 1 1 1)),
  ((1 1 1, 1 0 1, 1 0 0, 1 1 0, 1 1 1)),
  ((1 1 1, 1 1 0, 0 1 0, 0 1 1, 1 1 1))
)
```
Which is 6 polygons describing the 6 side surfaces of the box.

So the question becomes, what do you need from the Z-index? Do you need to be able to filter based on the height?

**Comment by sudhamani1983** [comment]
We need Z-index to facilitate having different building levels. Do you have any suggestions how to handle this in SensorthingAPI.

**Comment by hylkevds** [comment]
I think the easiest, quick, way is to put the floor nr in the properties of the Thing (for static things) or the Observation (for moving things). That way you can easily filter on those without having to build large 3d spatial queries.

**Comment by chhonker** [comment]
I'm storing FeatureOfInterest as 3D point 
`"encodingType": "application/vnd.geo+json",
"feature": {
"type": "Point",
"coordinates": [
93.0,
0.0,
302.1099853515625
]
},`
Now, I want to filter observations based on their location within a cube. Any help with the query.

**Comment by hylkevds** [comment]
The official way would be to use a filter for st_within, with a 3D POLYHEDRALSURFACE as one of the parameters.
The much easier, but less official way would probably be to directly filter on the GeoJSON with somethings like:

`$filter=feature/coordinates[2] gt 1.5 and feature/coordinates[2] lt 2.5`

coordinates[2] is the third coordinate of the point, and thus the altitude. Of course, this only works for Points.

**Comment by chhonker** [comment]
I'm running postgres version.
`PostgreSQL 9.5.10 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit`

on above request `http://localhost:8080/sensor/v1.0/FeaturesOfInterest?$filter=feature/coordinates[2] gt 1.5 and feature/coordinates[2] lt 2.5`
 it returns the below error, (_but on treating values as string eg. '1.5' and '2.5' it returns wrong result_)

`20:50:06.827 [http-bio-19201-exec-38] ERROR  d.f.i.ilt.sta.service.Service - 
com.querydsl.core.QueryException: Caught PSQLException for select "e1"."ID", "e1"."ID", "e1"."NAME", "e1"."DESCRIPTION", "e1"."ENCODING_TYPE", "e1"."FEATURE", "e1"."GEOM"
from "FEATURES" "e1"
where "e1"."FEATURE"::jsonb#>'{ coordinates,2 }' > to_jsonb(?) and jsonb_typeof("e1"."FEATURE"::jsonb#>'{ coordinates,2 }') = ? and ("e1"."FEATURE"::jsonb#>'{ coordinates,2 }' < to_jsonb(?) and jsonb_typeof("e1"."FEATURE"::jsonb#>'{ coordinates,2 }') = ?)
order by "e1"."ID" asc
limit ?
	at com.querydsl.sql.DefaultSQLExceptionTranslator.translate(DefaultSQLExceptionTranslator.java:50)
	at com.querydsl.sql.Configuration.translate(Configuration.java:459)
	at com.querydsl.sql.AbstractSQLQuery.fetch(AbstractSQLQuery.java:502)
	at de.fraunhofer.iosb.ilt.sta.persistence.postgres.EntityCreator.visit(EntityCreator.java:199)
	at de.fraunhofer.iosb.ilt.sta.path.EntitySetPathElement.visit(EntitySetPathElement.java:58)
	at de.fraunhofer.iosb.ilt.sta.persistence.postgres.PostgresPersistenceManager.get(PostgresPersistenceManager.java:446)
	at de.fraunhofer.iosb.ilt.sta.service.Service.executeGet(Service.java:145)
	at de.fraunhofer.iosb.ilt.sta.service.Service.execute(Service.java:75)
	at de.fraunhofer.iosb.ilt.sta.Servlet_1_0.executeService(Servlet_1_0.java:91)
	at de.fraunhofer.iosb.ilt.sta.Servlet_1_0.processGetRequest(Servlet_1_0.java:67)
	at de.fraunhofer.iosb.ilt.sta.Servlet_1_0.doGet(Servlet_1_0.java:135)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at de.fraunhofer.iosb.ilt.sta.Servlet_1_0.service(Servlet_1_0.java:173)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:436)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:177)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: function to_jsonb(double precision) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 185
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
	at com.querydsl.sql.AbstractSQLQuery.fetch(AbstractSQLQuery.java:446)
	... 34 common frames omitted
20:50:06.886 [http-bio-19201-exec-38] INFO  d.f.i.i.s.p.p.PostgresPersistenceManager - Rolling back changes.`

@hylkevds could you please help figure out the issue.

**Comment by hylkevds** [comment]
That error surprises me:
`ERROR: function to_jsonb(double precision) does not exist`

PostgreSQL 9.5 should have that function:
https://www.postgresql.org/docs/9.5/static/functions-json.html

If you connect to your database, and run the query:
`select to_jsonb(1.5);`
What do you get?

**Comment by timoruohomaki** [comment]
Was there any update on the Postgre issue? I'm working on future specs on two types of use cases:
1) some environmental sensors have specific height requirement but there are two options (e.g. either at 2,0 or 4,0 meters) and a math correction function is used to 'fix' the height when alternative is used. In this case, the GeoJSON filter option sounds like the way to go if it works. 
2) when thinking about the interoperability with CityGML and IndoorGML or GIS in general, the z should be mandatory in order to prevent something crazy happening in the visualization. Also importing sensor locations from the IFC -model would need a generic and interoperable approach. In the IFC and GML cases, generating 6 polyhedralsurfaces might not be a problem, but collecting the observations from larger area like city district might get a bit challenging.

**Comment by hylkevds** [comment]
I haven't had the time to look further into it.
If you want to experiment with it, currently the flattening happens in the `insertGeometry` method in the 
`EntityInserter` class in the three back-end implementations. You'll need to change the `ST_Force2D` to a `ST_Force3D` there.
The tables are defined in `src/main/resources/liquibase/tables*.xml`, you'll have to change the columns to use `GeometryZ` there.

**Comment by timoruohomaki** [comment]
Ok thanks for this, we'll try that after we get the sensors up and running
